databases:
  - name: edukado_web_postgres
    ipAllowList: []

services:
  - type: web
    name: edukado_web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: edukado_web_postgres
          property: connectionString
  - type: redis
    name: edukado_web_redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
