databases:
  - name: edukado_web
    databaseName: edukado_web
    user: edukado_web

services:
  - type: web
    name: edukado_web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edukado_web
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
